version: "3"
services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: magzhan2005
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data

  api:
    build: ./api
    image: altinbekpin/echo1:api-v2
    container_name: api
    restart: always
    volumes:
      - ./api/:/app
    depends_on:
      - db
    expose:
      - 9000
    ports:
      - "5001:9000"
  ui:
    build: ./ui
    image: altinbekpin/echo1:ui-v2
    container_name: ui
    restart: always
    expose:
      - 80
    ports:
      - "8080:80"
  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8000:8000"
      - "8001:80"
