# Generated by Django 3.2.3 on 2021-09-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20200531_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ontotext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Мәтіні')),
                ('owl', models.TextField(blank=True, verbose_name='Owl мәтіні')),
                ('json', models.TextField(blank=True, verbose_name='Json мәтіні')),
                ('name', models.CharField(max_length=200, verbose_name='Атауы')),
            ],
        ),
        migrations.AlterField(
            model_name='ontology',
            name='text',
            field=models.TextField(blank=True, verbose_name='Мәтіні'),
        ),
    ]
