# Generated by Django 3.2.3 on 2021-10-08 09:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0004_auto_20210924_0740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ontology',
            new_name='MyOntology',
        ),
    ]
