# Generated by Django 3.2.8 on 2021-12-03 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0005_rename_ontology_myontology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Құрылған уақыты')),
                ('name', models.CharField(max_length=200, verbose_name='Атауы')),
                ('text', models.TextField(blank=True, verbose_name='Мәтіні')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Мәтіні')),
                ('qtype', models.IntegerField(verbose_name='Сұрақ түрі')),
                ('level', models.IntegerField(default=0, verbose_name='Деңгейі')),
                ('answer', models.TextField(blank=True, verbose_name='Жауабы')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.topic')),
            ],
        ),
    ]
